services:
  drupal:
    image: drupal:9.1.14
    volumes:
    - /var/www/html/modules
    - /var/www/html/profiles
    - /var/www/html/themes
    - /var/www/html/sites
    restart: always
    ports:
      - '8080:80'

  postgres:
    image: postgres:14.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: pass
    restart: always